// https://v3.nuxtjs.org/api/configuration/nuxt.config
export default defineNuxtConfig({
  devtools: { enabled: true },
  future: { compatibilityVersion: 4 },

  modules: ['@nuxtjs/i18n'],

  i18n: {
    lazy: true,
    defaultLocale: 'en-US',
    locales: [
      {
        channel: 'arg-es',
        file: 'ja.json',
        dir: 'ltr',
        code: 'es-AR',
      },
      {
        channel: 'aus-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-AU',
      },
      {
        channel: 'aut-de',
        file: 'en.json',
        dir: 'ltr',
        code: 'de-AT',
      },
      {
        channel: 'bel-fr',
        file: 'en.json',
        dir: 'ltr',
        code: 'fr-BE',
      },
      {
        channel: 'bel-nl',
        file: 'en.json',
        dir: 'ltr',
        code: 'nl-BE',
      },
      {
        channel: 'bgr-bg',
        file: 'en.json',
        dir: 'ltr',
        code: 'bg-BG',
      },
      {
        channel: 'bih-sr',
        file: 'en.json',
        dir: 'ltr',
        code: 'sr-BA',
      },
      {
        channel: 'bra-pt',
        file: 'en.json',
        dir: 'ltr',
        code: 'pt-BR',
      },
      {
        channel: 'che-de',
        file: 'en.json',
        dir: 'ltr',
        code: 'de-CH',
      },
      {
        channel: 'che-fr',
        file: 'en.json',
        dir: 'ltr',
        code: 'fr-CH',
      },
      {
        channel: 'chl-es',
        file: 'en.json',
        dir: 'ltr',
        code: 'es-CL',
      },
      {
        channel: 'cze-cs',
        file: 'en.json',
        dir: 'ltr',
        code: 'cs-CZ',
      },
      {
        channel: 'deu-de',
        file: 'en.json',
        dir: 'ltr',
        code: 'de-DE',
      },
      {
        channel: 'dnk-da',
        file: 'en.json',
        dir: 'ltr',
        code: 'da-DK',
      },
      {
        channel: 'esp-es',
        file: 'en.json',
        dir: 'ltr',
        code: 'es-ES',
      },
      {
        channel: 'est-ee',
        file: 'en.json',
        dir: 'ltr',
        code: 'et-EE',
      },
      {
        channel: 'fin-fi',
        file: 'en.json',
        dir: 'ltr',
        code: 'fi-FI',
      },
      {
        channel: 'fr-fr',
        file: 'en.json',
        dir: 'ltr',
        code: 'fr-FR',
      },
      {
        channel: 'gbr-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-GB',
      },
      {
        channel: 'geo-ka',
        file: 'en.json',
        dir: 'ltr',
        code: 'ka-GE',
      },
      {
        channel: 'grc-el',
        file: 'en.json',
        dir: 'ltr',
        code: 'el-GR',
      },
      {
        channel: 'hrv-hr',
        file: 'en.json',
        dir: 'ltr',
        code: 'hr-HR',
      },
      {
        channel: 'hun-hu',
        file: 'en.json',
        dir: 'ltr',
        code: 'hu-HU',
      },
      {
        channel: 'isl-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-IS',
      },
      {
        channel: 'isr-he',
        file: 'en.json',
        dir: 'rtl',
        code: 'he-IL',
      },
      {
        channel: 'ita-it',
        file: 'en.json',
        dir: 'ltr',
        code: 'it-IT',
      },
      {
        channel: 'kaz-ru',
        file: 'en.json',
        dir: 'ltr',
        code: 'ru-KZ',
      },
      {
        channel: 'kor-kr',
        file: 'en.json',
        dir: 'ltr',
        code: 'ko-KR',
      },
      {
        channel: 'ltu-lt',
        file: 'en.json',
        dir: 'ltr',
        code: 'lt-LT',
      },
      {
        channel: 'lva-lv',
        file: 'en.json',
        dir: 'ltr',
        code: 'lv-LV',
      },
      {
        channel: 'nld-nl',
        file: 'nl.json',
        dir: 'ltr',
        code: 'nl-NL',
      },
      {
        channel: 'nor-no',
        file: 'en.json',
        dir: 'ltr',
        code: 'nn-NO',
      },
      {
        channel: 'nz-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-NZ',
      },
      {
        channel: 'pol-pl',
        file: 'en.json',
        dir: 'ltr',
        code: 'pl-PL',
      },
      {
        channel: 'rou-ro',
        file: 'en.json',
        dir: 'ltr',
        code: 'ro-RO',
      },
      {
        channel: 'rus-ru',
        file: 'en.json',
        dir: 'ltr',
        code: 'ru-RU',
      },
      {
        channel: 'sau-ar',
        dir: 'rtl',
        code: 'ar-SA',
      },
      {
        channel: 'sau-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-SA',
      },
      {
        channel: 'slv-si',
        file: 'en.json',
        dir: 'ltr',
        code: 'sl-SI',
      },
      {
        channel: 'srb-sr',
        file: 'en.json',
        dir: 'ltr',
        code: 'sr-RS',
      },
      {
        channel: 'svk-sk',
        file: 'en.json',
        dir: 'ltr',
        code: 'sk-SK',
      },
      {
        channel: 'swe-sv',
        file: 'en.json',
        dir: 'ltr',
        code: 'sv-SE',
      },
      {
        channel: 'tur-tr',
        file: 'en.json',
        dir: 'ltr',
        code: 'tr-TR',
      },
      {
        channel: 'twn-zh',
        file: 'en.json',
        dir: 'ltr',
        code: 'zh-TW',
      },
      {
        channel: 'ukr-ua',
        file: 'en.json',
        dir: 'ltr',
        code: 'uk-UA',
      },
      {
        channel: 'us-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-US',
      },
      {
        channel: 'zaf-en',
        file: 'en.json',
        dir: 'ltr',
        code: 'en-ZA',
      },
    ],
    detectBrowserLanguage: false,
  },

  compatibilityDate: '2024-11-15',
});
